function J = solveJacobian(p, theta_in, q1_in, q2_in, q3_in, q4_in)

syms x y theta q1 q2 q3 q4

J_sym = [cos(theta)*((11*cos(q2)*sin(q1))/50 - cos(q1)*((11*sin(q2))/50 + 11/50)) - sin(theta)*((11*cos(q1)*cos(q2))/50 + sin(q1)*((11*sin(q2))/50 + 11/50)), cos(theta)*((11*cos(q1)*sin(q2))/50 - (11*cos(q2)*sin(q1))/50) + sin(theta)*((11*cos(q1)*cos(q2))/50 + (11*sin(q1)*sin(q2))/50),                                                                                                                                                     0,                                                                                                                               0;
         cos(theta)*((11*cos(q1)*cos(q2))/50 + sin(q1)*((11*sin(q2))/50 + 11/50)) + sin(theta)*((11*cos(q2)*sin(q1))/50 - cos(q1)*((11*sin(q2))/50 + 11/50)), sin(theta)*((11*cos(q1)*sin(q2))/50 - (11*cos(q2)*sin(q1))/50) - cos(theta)*((11*cos(q1)*cos(q2))/50 + (11*sin(q1)*sin(q2))/50),                                                                                                                                                     0,                                                                                                                               0;
                                                                                                                                                           0,                                                                                                                               0,                                                                                                                                                     0,                                                                                                                               0;
                                                                                                                                                           0,                                                                                                                               0, - cos(theta)*((11*sin(q3)*sin(q4))/50 - cos(q3)*((11*cos(q4))/50 + 11/50)) - sin(theta)*((11*cos(q3)*sin(q4))/50 + sin(q3)*((11*cos(q4))/50 + 11/50)), cos(theta)*((11*cos(q3)*cos(q4))/50 - (11*sin(q3)*sin(q4))/50) - sin(theta)*((11*cos(q3)*sin(q4))/50 + (11*cos(q4)*sin(q3))/50);
                                                                                                                                                           0,                                                                                                                               0,   cos(theta)*((11*cos(q3)*sin(q4))/50 + sin(q3)*((11*cos(q4))/50 + 11/50)) - sin(theta)*((11*sin(q3)*sin(q4))/50 - cos(q3)*((11*cos(q4))/50 + 11/50)), cos(theta)*((11*cos(q3)*sin(q4))/50 + (11*cos(q4)*sin(q3))/50) + sin(theta)*((11*cos(q3)*cos(q4))/50 - (11*sin(q3)*sin(q4))/50);
                                                                                                                                                           0,                                                                                                                               0,                                                                                                                                                     0,                                                                                                                               0];

 
J = double(subs(J_sym, [x y theta q1 q2 q3 q4], [p(1) p(2) theta_in q1_in q2_in q3_in q4_in]));

end